# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f10475cf9c385708e9271d059c48de252b2f8c06b912a1d05ace4b0f37fd11c65c67841f0d0b4d1c37d61abe1b914724afd5b12eb3e6df29e7e13311afaa882

test:
  secret_key_base: 0e664b9f4e0502e1be29fb94dec838532b6de9237fdee1149401c8a4b020ce3cfc48425019ce9202e47863fc3005c20d35f297dcbb4f4023d6cf89757ddcc699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
